### PR TITLE
Updated Committee Heads. Other Committee info needs to be added such as ...

### PR DESCRIPTION
**Pull request by jaffes2**
...Tutoring, Sponsorship, and Website.

### CODE REVIEW

**Comment by jaffes2** [comment]
Updated Events page + pictures

**Comment by jaffes2** [comment]
events

**Comment by gonsie** [comment]
Is this ready to be merged or does "events" mean something?

**Comment by jaffes2** [comment]
Ready to be merged.  I accidentally closed the pull request

**Pull request merged**
